// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects/index'
import { Route as AppProjectsProjectIdRouteRouteImport } from './routes/_app/projects/$projectId/route'
import { Route as ClientBriefTokenRouteImport } from './routes/client/brief/$token'
import { Route as AppProjectsProjectIdIndexRouteImport } from './routes/_app/projects/$projectId/index'
import { Route as AppProjectsProjectIdActivityRouteImport } from './routes/_app/projects/$projectId/activity'
import { Route as AppProjectsProjectIdBriefRouteImport } from './routes/_app/projects/$projectId/brief'
import { Route as AppProjectsProjectIdChangesRouteImport } from './routes/_app/projects/$projectId/changes'
import { Route as AppProjectsProjectIdFilesRouteImport } from './routes/_app/projects/$projectId/files'
import { Route as AppProjectsProjectIdScopeRouteImport } from './routes/_app/projects/$projectId/scope'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdRouteRoute =
  AppProjectsProjectIdRouteRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AppRoute,
  } as any)
const ClientBriefTokenRoute = ClientBriefTokenRouteImport.update({
  id: '/client/brief/$token',
  path: '/client/brief/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectsProjectIdIndexRoute =
  AppProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsProjectIdRouteRoute,
  } as any)
const AppProjectsProjectIdActivityRoute =
  AppProjectsProjectIdActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AppProjectsProjectIdRouteRoute,
  } as any)
const AppProjectsProjectIdBriefRoute =
  AppProjectsProjectIdBriefRouteImport.update({
    id: '/brief',
    path: '/brief',
    getParentRoute: () => AppProjectsProjectIdRouteRoute,
  } as any)
const AppProjectsProjectIdChangesRoute =
  AppProjectsProjectIdChangesRouteImport.update({
    id: '/changes',
    path: '/changes',
    getParentRoute: () => AppProjectsProjectIdRouteRoute,
  } as any)
const AppProjectsProjectIdFilesRoute =
  AppProjectsProjectIdFilesRouteImport.update({
    id: '/files',
    path: '/files',
    getParentRoute: () => AppProjectsProjectIdRouteRoute,
  } as any)
const AppProjectsProjectIdScopeRoute =
  AppProjectsProjectIdScopeRouteImport.update({
    id: '/scope',
    path: '/scope',
    getParentRoute: () => AppProjectsProjectIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRouteRouteWithChildren
  '/client/brief/$token': typeof ClientBriefTokenRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/projects/$projectId/activity': typeof AppProjectsProjectIdActivityRoute
  '/projects/$projectId/brief': typeof AppProjectsProjectIdBriefRoute
  '/projects/$projectId/changes': typeof AppProjectsProjectIdChangesRoute
  '/projects/$projectId/files': typeof AppProjectsProjectIdFilesRoute
  '/projects/$projectId/scope': typeof AppProjectsProjectIdScopeRoute
  '/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/client/brief/$token': typeof ClientBriefTokenRoute
  '/projects': typeof AppProjectsIndexRoute
  '/projects/$projectId/activity': typeof AppProjectsProjectIdActivityRoute
  '/projects/$projectId/brief': typeof AppProjectsProjectIdBriefRoute
  '/projects/$projectId/changes': typeof AppProjectsProjectIdChangesRoute
  '/projects/$projectId/files': typeof AppProjectsProjectIdFilesRoute
  '/projects/$projectId/scope': typeof AppProjectsProjectIdScopeRoute
  '/projects/$projectId': typeof AppProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRouteRouteWithChildren
  '/client/brief/$token': typeof ClientBriefTokenRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/projects/$projectId/activity': typeof AppProjectsProjectIdActivityRoute
  '/_app/projects/$projectId/brief': typeof AppProjectsProjectIdBriefRoute
  '/_app/projects/$projectId/changes': typeof AppProjectsProjectIdChangesRoute
  '/_app/projects/$projectId/files': typeof AppProjectsProjectIdFilesRoute
  '/_app/projects/$projectId/scope': typeof AppProjectsProjectIdScopeRoute
  '/_app/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard'
    | '/settings'
    | '/projects/$projectId'
    | '/client/brief/$token'
    | '/projects/'
    | '/projects/$projectId/activity'
    | '/projects/$projectId/brief'
    | '/projects/$projectId/changes'
    | '/projects/$projectId/files'
    | '/projects/$projectId/scope'
    | '/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard'
    | '/settings'
    | '/client/brief/$token'
    | '/projects'
    | '/projects/$projectId/activity'
    | '/projects/$projectId/brief'
    | '/projects/$projectId/changes'
    | '/projects/$projectId/files'
    | '/projects/$projectId/scope'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/_app/dashboard'
    | '/_app/settings'
    | '/_app/projects/$projectId'
    | '/client/brief/$token'
    | '/_app/projects/'
    | '/_app/projects/$projectId/activity'
    | '/_app/projects/$projectId/brief'
    | '/_app/projects/$projectId/changes'
    | '/_app/projects/$projectId/files'
    | '/_app/projects/$projectId/scope'
    | '/_app/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ClientBriefTokenRoute: typeof ClientBriefTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/client/brief/$token': {
      id: '/client/brief/$token'
      path: '/client/brief/$token'
      fullPath: '/client/brief/$token'
      preLoaderRoute: typeof ClientBriefTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/projects/$projectId/': {
      id: '/_app/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AppProjectsProjectIdIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdRouteRoute
    }
    '/_app/projects/$projectId/activity': {
      id: '/_app/projects/$projectId/activity'
      path: '/activity'
      fullPath: '/projects/$projectId/activity'
      preLoaderRoute: typeof AppProjectsProjectIdActivityRouteImport
      parentRoute: typeof AppProjectsProjectIdRouteRoute
    }
    '/_app/projects/$projectId/brief': {
      id: '/_app/projects/$projectId/brief'
      path: '/brief'
      fullPath: '/projects/$projectId/brief'
      preLoaderRoute: typeof AppProjectsProjectIdBriefRouteImport
      parentRoute: typeof AppProjectsProjectIdRouteRoute
    }
    '/_app/projects/$projectId/changes': {
      id: '/_app/projects/$projectId/changes'
      path: '/changes'
      fullPath: '/projects/$projectId/changes'
      preLoaderRoute: typeof AppProjectsProjectIdChangesRouteImport
      parentRoute: typeof AppProjectsProjectIdRouteRoute
    }
    '/_app/projects/$projectId/files': {
      id: '/_app/projects/$projectId/files'
      path: '/files'
      fullPath: '/projects/$projectId/files'
      preLoaderRoute: typeof AppProjectsProjectIdFilesRouteImport
      parentRoute: typeof AppProjectsProjectIdRouteRoute
    }
    '/_app/projects/$projectId/scope': {
      id: '/_app/projects/$projectId/scope'
      path: '/scope'
      fullPath: '/projects/$projectId/scope'
      preLoaderRoute: typeof AppProjectsProjectIdScopeRouteImport
      parentRoute: typeof AppProjectsProjectIdRouteRoute
    }
  }
}

interface AppProjectsProjectIdRouteRouteChildren {
  AppProjectsProjectIdActivityRoute: typeof AppProjectsProjectIdActivityRoute
  AppProjectsProjectIdBriefRoute: typeof AppProjectsProjectIdBriefRoute
  AppProjectsProjectIdChangesRoute: typeof AppProjectsProjectIdChangesRoute
  AppProjectsProjectIdFilesRoute: typeof AppProjectsProjectIdFilesRoute
  AppProjectsProjectIdScopeRoute: typeof AppProjectsProjectIdScopeRoute
  AppProjectsProjectIdIndexRoute: typeof AppProjectsProjectIdIndexRoute
}

const AppProjectsProjectIdRouteRouteChildren: AppProjectsProjectIdRouteRouteChildren =
  {
    AppProjectsProjectIdActivityRoute: AppProjectsProjectIdActivityRoute,
    AppProjectsProjectIdBriefRoute: AppProjectsProjectIdBriefRoute,
    AppProjectsProjectIdChangesRoute: AppProjectsProjectIdChangesRoute,
    AppProjectsProjectIdFilesRoute: AppProjectsProjectIdFilesRoute,
    AppProjectsProjectIdScopeRoute: AppProjectsProjectIdScopeRoute,
    AppProjectsProjectIdIndexRoute: AppProjectsProjectIdIndexRoute,
  }

const AppProjectsProjectIdRouteRouteWithChildren =
  AppProjectsProjectIdRouteRoute._addFileChildren(
    AppProjectsProjectIdRouteRouteChildren,
  )

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppProjectsProjectIdRouteRoute: typeof AppProjectsProjectIdRouteRouteWithChildren
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppProjectsProjectIdRouteRoute: AppProjectsProjectIdRouteRouteWithChildren,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ClientBriefTokenRoute: ClientBriefTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
